spring:
  jpa:
    hibernate:
      ddl-auto: create-drop  # (1) ??? ?? ??
    show-sql: true      # (2) SQL ?? ??
    properties:
      hibernate:
        format_sql: true  # (3) SQL pretty print
server:
  servlet:
    encoding:
      charset: UTF-8
      force: true